[package]
name = "exonum-merkledb"
version = "0.10.0"
edition = "2018"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/"
repository = "https://github.com/exonum/exonum"
documentation = "https://docs.rs/exonum-merkledb"
readme = "README.md"
license = "Apache-2.0"

# keywords = ["exonum", "cryptography", "library"]
# categories = ["cryptography", "hashing"]
# description = "Cryptography related types, constants, traits and functions."

[dependencies]
byteorder = "1.2"
chrono = "0.4.6"
exonum_rocksdb = "0.7.4"
exonum-crypto = { git = "https://github.com/exonum/exonum", rev = "5dcbfc5561bfaf9f9a3c8264f7bdba463bf074ba" }
failure = "0.1.3"
hex = "0.3.2"
rust_decimal = "0.10.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempfile = "3.0"
uuid = "0.7.1"

[dev-dependencies]
criterion = "0.2"
rand = "0.6.1"
rand_xorshift = "0.1.0"

[[bench]]
name = "criterion"
path = "benches/lib.rs"
harness = false